---
- name: Installer Jenkins sur Debian 12
  hosts: cicdhub
  become: yes

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Java (OpenJDK 17)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Télécharger la clé GPG officielle de Jenkins
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Ajouter le dépôt Jenkins (compatible Debian 12)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins

    - name: Mettre à jour la liste des paquets après ajout du dépôt
      apt:
        update_cache: yes

    - name: Installer Jenkins
      apt:
        name: jenkins
        state: present

    - name: Démarrer et activer Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Attendre que Jenkins crée le mot de passe initial
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        state: present
        delay: 5
        timeout: 60

    - name: Afficher le mot de passe initial de Jenkins
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Mot de passe initial de Jenkins
      debug:
        msg: "Mot de passe initial : {{ jenkins_password.stdout }}"